<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the MV Labs version of the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a starting point for you to begin building your application on ZF2. Compared to the original version we\'ve enabled by default a few features which we recurrently use in our projects.'), '<a href="https://github.com/mvlabs/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/mvlabs/ZendSkeletonApplication" target="_blank"><?php echo $this->translate('Check out the Application GitHub repository for more info...') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help while developing with ZF2,
                		you may reach the ZF development team via IRC: %s#zftalk on Freenode%s.
                		It\'s a nice knit community with plenty of members ready to help. You may also subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

     <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Enterprise Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('If the stakes are high, or you need enterprise grade support,
                		you can get in touch with us directly. We\'re from Italy and have half a dozen years of experience on Zend Framework.') ?></p>
						<a class="btn btn-success pull-right" href="http://www.mvlabs.it" target="_blank"><?php echo $this->translate('Get in touch with MV Labs') ?> &raquo;</a>
				</p>

            </div>
        </div>
    </div>

</div>
